<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Menu;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        $menus = [
            ['name'=>'Nasi Goreng Spesial',   'category'=>'makanan', 'price'=>35000, 'original_price'=>45000, 'image_url'=>'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop', 'rating'=>4.8, 'review_count'=>234, 'label'=>'best-seller', 'is_promo'=>true,  'is_new'=>false, 'description'=>'Nasi goreng dengan bumbu rahasia, telur mata sapi, dan ayam crispy'],
            ['name'=>'Ayam Bakar Madu',        'category'=>'makanan', 'price'=>45000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>189, 'label'=>'best-seller', 'is_promo'=>false, 'is_new'=>false, 'description'=>'Ayam bakar dengan saus madu spesial dan lalapan segar'],
            ['name'=>'Mie Goreng Seafood',     'category'=>'makanan', 'price'=>40000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&h=300&fit=crop', 'rating'=>4.7, 'review_count'=>156, 'label'=>'',           'is_promo'=>false, 'is_new'=>true,  'description'=>'Mie goreng dengan udang, cumi, dan sayuran segar'],
            ['name'=>'Sate Ayam Madura',       'category'=>'makanan', 'price'=>30000, 'original_price'=>38000, 'image_url'=>'https://images.unsplash.com/photo-1529563021893-cc83c992d75d?w=400&h=300&fit=crop', 'rating'=>4.6, 'review_count'=>312, 'label'=>'popular',     'is_promo'=>true,  'is_new'=>false, 'description'=>'10 tusuk sate ayam dengan bumbu kacang khas Madura'],
            ['name'=>'Gado-Gado',              'category'=>'makanan', 'price'=>28000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop', 'rating'=>4.6, 'review_count'=>143, 'label'=>'',           'is_promo'=>false, 'is_new'=>false, 'description'=>'Gado-gado dengan bumbu kacang khas dan kerupuk'],
            ['name'=>'Es Teh Manis',           'category'=>'minuman', 'price'=>8000,  'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop', 'rating'=>4.5, 'review_count'=>445, 'label'=>'popular',     'is_promo'=>false, 'is_new'=>false, 'description'=>'Teh manis segar dengan es batu pilihan'],
            ['name'=>'Jus Alpukat',            'category'=>'minuman', 'price'=>18000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400&h=300&fit=crop', 'rating'=>4.8, 'review_count'=>198, 'label'=>'best-seller', 'is_promo'=>false, 'is_new'=>false, 'description'=>'Jus alpukat segar dengan susu kental manis'],
            ['name'=>'Kopi Susu Kekinian',     'category'=>'minuman', 'price'=>22000, 'original_price'=>28000, 'image_url'=>'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>567, 'label'=>'best-seller', 'is_promo'=>true,  'is_new'=>false, 'description'=>'Kopi susu dengan espresso shot dan susu segar'],
            ['name'=>'Matcha Latte',           'category'=>'minuman', 'price'=>25000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=400&h=300&fit=crop', 'rating'=>4.7, 'review_count'=>123, 'label'=>'',           'is_promo'=>false, 'is_new'=>true,  'description'=>'Matcha premium dengan susu oat dan foam lembut'],
            ['name'=>'Cheesecake Strawberry',  'category'=>'dessert', 'price'=>32000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&h=300&fit=crop', 'rating'=>4.8, 'review_count'=>89,  'label'=>'new',         'is_promo'=>false, 'is_new'=>true,  'description'=>'Cheesecake lembut dengan topping strawberry segar'],
            ['name'=>'Brownies Coklat',        'category'=>'dessert', 'price'=>25000, 'original_price'=>30000, 'image_url'=>'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop', 'rating'=>4.6, 'review_count'=>145, 'label'=>'popular',     'is_promo'=>true,  'is_new'=>false, 'description'=>'Brownies coklat premium dengan topping almond'],
            ['name'=>'Es Krim Gelato',         'category'=>'dessert', 'price'=>28000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400&h=300&fit=crop', 'rating'=>4.7, 'review_count'=>201, 'label'=>'best-seller', 'is_promo'=>false, 'is_new'=>false, 'description'=>'Gelato Italia asli dengan berbagai pilihan rasa'],
            ['name'=>'Smoothie Bowl',          'category'=>'dessert', 'price'=>38000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1490323914169-4b57d0054c5a?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>76,  'label'=>'new',         'is_promo'=>false, 'is_new'=>true,  'description'=>'Smoothie bowl dengan granola, buah segar, dan madu'],
            ['name'=>'French Fries',           'category'=>'snack',   'price'=>20000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop', 'rating'=>4.5, 'review_count'=>334, 'label'=>'popular',     'is_promo'=>false, 'is_new'=>false, 'description'=>'Kentang goreng crispy dengan saus pilihan'],
            ['name'=>'Onion Ring',             'category'=>'snack',   'price'=>22000, 'original_price'=>27000, 'image_url'=>'https://images.unsplash.com/photo-1639024471283-03518883512d?w=400&h=300&fit=crop', 'rating'=>4.4, 'review_count'=>167, 'label'=>'',           'is_promo'=>true,  'is_new'=>false, 'description'=>'Bawang bombay goreng crispy dengan saus ranch'],
            ['name'=>'Chicken Wings',          'category'=>'snack',   'price'=>35000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=400&h=300&fit=crop', 'rating'=>4.8, 'review_count'=>278, 'label'=>'best-seller', 'is_promo'=>false, 'is_new'=>false, 'description'=>'6 pcs chicken wings dengan saus BBQ pedas'],
            ['name'=>'Paket Hemat A',          'category'=>'paket',   'price'=>55000, 'original_price'=>75000, 'image_url'=>'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop', 'rating'=>4.8, 'review_count'=>312, 'label'=>'best-seller', 'is_promo'=>true,  'is_new'=>false, 'description'=>'Nasi Goreng + Ayam Goreng + Es Teh Manis'],
            ['name'=>'Paket Keluarga',         'category'=>'paket',   'price'=>150000,'original_price'=>200000,'image_url'=>'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>189, 'label'=>'best-seller', 'is_promo'=>true,  'is_new'=>false, 'description'=>'4 Nasi + 4 Lauk pilihan + 4 Minuman + Dessert'],
            ['name'=>'Paket Romantis',         'category'=>'paket',   'price'=>120000,'original_price'=>160000,'image_url'=>'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop', 'rating'=>4.7, 'review_count'=>98,  'label'=>'popular',     'is_promo'=>true,  'is_new'=>true,  'description'=>'2 Steak + 2 Minuman + Dessert + Candle Light'],
            ['name'=>'Paket Bisnis',           'category'=>'paket',   'price'=>45000, 'original_price'=>60000, 'image_url'=>'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop', 'rating'=>4.5, 'review_count'=>234, 'label'=>'',           'is_promo'=>true,  'is_new'=>false, 'description'=>'Nasi + Lauk + Sayur + Minuman (cocok untuk makan siang)'],

            // ── Seafood ──
            ['name'=>'Udang Bakar Madu',         'category'=>'seafood', 'price'=>65000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>178, 'label'=>'best-seller', 'is_promo'=>false, 'is_new'=>false, 'description'=>'Udang segar bakar dengan saus madu spesial dan lalapan'],
            ['name'=>'Ikan Gurame Goreng',       'category'=>'seafood', 'price'=>55000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=400&h=300&fit=crop', 'rating'=>4.8, 'review_count'=>245, 'label'=>'best-seller', 'is_promo'=>false, 'is_new'=>false, 'description'=>'Gurame segar goreng krispi dengan sambal terasi dan lalapan'],
            ['name'=>'Cumi Saus Tiram',          'category'=>'seafood', 'price'=>48000, 'original_price'=>58000, 'image_url'=>'https://images.unsplash.com/photo-1565680018434-b51d7e6e8305?w=400&h=300&fit=crop', 'rating'=>4.7, 'review_count'=>134, 'label'=>'popular',     'is_promo'=>true,  'is_new'=>false, 'description'=>'Cumi segar dimasak dengan saus tiram dan paprika'],
            ['name'=>'Kerapu Steam',             'category'=>'seafood', 'price'=>85000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>89,  'label'=>'new',         'is_promo'=>false, 'is_new'=>true,  'description'=>'Ikan kerapu kukus dengan jahe, kecap, dan bawang'],
            ['name'=>'Lobster Thermidor',        'category'=>'seafood', 'price'=>150000,'original_price'=>180000,'image_url'=>'https://images.unsplash.com/photo-1553621042-f6e147245754?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>67,  'label'=>'',            'is_promo'=>true,  'is_new'=>false, 'description'=>'Lobster premium dengan saus thermidor keju dan herbs'],

            // ── Aneka Snack ──
            ['name'=>'Pisang Goreng Keju',       'category'=>'aneka-snack', 'price'=>15000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1600326145359-3a44909d1a39?w=400&h=300&fit=crop', 'rating'=>4.6, 'review_count'=>289, 'label'=>'popular',     'is_promo'=>false, 'is_new'=>false, 'description'=>'Pisang goreng crispy dengan topping keju dan susu kental manis'],
            ['name'=>'Tahu Crispy',              'category'=>'aneka-snack', 'price'=>12000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop', 'rating'=>4.5, 'review_count'=>312, 'label'=>'popular',     'is_promo'=>false, 'is_new'=>false, 'description'=>'Tahu goreng crispy renyah dengan sambal kecap'],
            ['name'=>'Risoles Mayo',             'category'=>'aneka-snack', 'price'=>8000,  'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1519864600265-abb23847a447?w=400&h=300&fit=crop', 'rating'=>4.7, 'review_count'=>456, 'label'=>'best-seller', 'is_promo'=>false, 'is_new'=>false, 'description'=>'Risoles isi ragout sayuran dan mayonaise, goreng keemasan'],
            ['name'=>'Combro & Misro',           'category'=>'aneka-snack', 'price'=>10000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop', 'rating'=>4.4, 'review_count'=>198, 'label'=>'',            'is_promo'=>false, 'is_new'=>false, 'description'=>'Singkong goreng isi oncom (combro) dan gula merah (misro)'],
            ['name'=>'Dimsum Ayam Udang',        'category'=>'aneka-snack', 'price'=>25000, 'original_price'=>30000, 'image_url'=>'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&h=300&fit=crop', 'rating'=>4.8, 'review_count'=>267, 'label'=>'best-seller', 'is_promo'=>true,  'is_new'=>false, 'description'=>'Dimsum kukus isi campuran ayam dan udang, 5 pcs'],

            // ── Aneka Sayur ──
            ['name'=>'Sayur Asem',               'category'=>'aneka-sayur', 'price'=>15000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop', 'rating'=>4.6, 'review_count'=>234, 'label'=>'popular',     'is_promo'=>false, 'is_new'=>false, 'description'=>'Sayur asem segar dengan jagung, kacang panjang, dan labu siam'],
            ['name'=>'Cap Cay Goreng',           'category'=>'aneka-sayur', 'price'=>22000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop', 'rating'=>4.7, 'review_count'=>189, 'label'=>'best-seller', 'is_promo'=>false, 'is_new'=>false, 'description'=>'Cap cay goreng dengan 10 macam sayuran segar dan saus tiram'],
            ['name'=>'Urap Sayur',               'category'=>'aneka-sayur', 'price'=>12000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1543339308-d595c0cd10b2?w=400&h=300&fit=crop', 'rating'=>4.5, 'review_count'=>156, 'label'=>'',            'is_promo'=>false, 'is_new'=>false, 'description'=>'Sayuran rebus dengan bumbu kelapa parut khas Jawa'],
            ['name'=>'Gulai Daun Singkong',      'category'=>'aneka-sayur', 'price'=>10000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop', 'rating'=>4.6, 'review_count'=>178, 'label'=>'popular',     'is_promo'=>false, 'is_new'=>false, 'description'=>'Daun singkong dimasak gulau santan bumbu Padang'],
            ['name'=>'Plecing Kangkung',         'category'=>'aneka-sayur', 'price'=>12000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop', 'rating'=>4.7, 'review_count'=>201, 'label'=>'new',         'is_promo'=>false, 'is_new'=>true,  'description'=>'Kangkung segar dengan sambal plecing pedas khas Lombok'],

            // ── Nasi Kotak ──
            ['name'=>'Nasi Kotak Ayam Goreng',   'category'=>'nasi-kotak', 'price'=>35000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&h=300&fit=crop', 'rating'=>4.7, 'review_count'=>312, 'label'=>'best-seller', 'is_promo'=>false, 'is_new'=>false, 'description'=>'Nasi putih + ayam goreng + sayur + sambal + kerupuk, dalam kotak'],
            ['name'=>'Nasi Kotak Rendang',       'category'=>'nasi-kotak', 'price'=>40000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>267, 'label'=>'best-seller', 'is_promo'=>false, 'is_new'=>false, 'description'=>'Nasi putih + rendang sapi + telur balado + sayur, dalam kotak'],
            ['name'=>'Nasi Kotak Ikan Bakar',    'category'=>'nasi-kotak', 'price'=>38000, 'original_price'=>45000, 'image_url'=>'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=400&h=300&fit=crop', 'rating'=>4.8, 'review_count'=>189, 'label'=>'popular',     'is_promo'=>true,  'is_new'=>false, 'description'=>'Nasi putih + ikan bakar + lalapan + sambal terasi, dalam kotak'],
            ['name'=>'Nasi Kotak Sate Ayam',     'category'=>'nasi-kotak', 'price'=>32000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1529563021893-cc83c992d75d?w=400&h=300&fit=crop', 'rating'=>4.6, 'review_count'=>234, 'label'=>'popular',     'is_promo'=>false, 'is_new'=>false, 'description'=>'Nasi putih + 5 tusuk sate ayam + lontong + acar, dalam kotak'],
            ['name'=>'Nasi Kotak Spesial',       'category'=>'nasi-kotak', 'price'=>50000, 'original_price'=>60000, 'image_url'=>'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>145, 'label'=>'new',         'is_promo'=>true,  'is_new'=>true,  'description'=>'Nasi + ayam + ikan + udang + sayur + dessert + minuman, paket lengkap'],

            // ── Acara Khusus ──
            ['name'=>'Paket Ulang Tahun',        'category'=>'acara-khusus', 'price'=>500000, 'original_price'=>650000, 'image_url'=>'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>78,  'label'=>'popular',     'is_promo'=>true,  'is_new'=>false, 'description'=>'Paket untuk 20 orang: nasi, lauk, kue ulang tahun, dekorasi sederhana'],
            ['name'=>'Paket Reuni',              'category'=>'acara-khusus', 'price'=>750000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop', 'rating'=>4.8, 'review_count'=>56,  'label'=>'',            'is_promo'=>false, 'is_new'=>false, 'description'=>'Paket buffet untuk 30 orang: aneka lauk, nasi, dessert, dan minuman'],
            ['name'=>'Paket Lamaran',            'category'=>'acara-khusus', 'price'=>1500000,'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>34,  'label'=>'new',         'is_promo'=>false, 'is_new'=>true,  'description'=>'Paket eksklusif 50 orang: dekorasi, buffet premium, kue, dan souvenir'],
            ['name'=>'Paket Gathering Kantor',   'category'=>'acara-khusus', 'price'=>2000000,'original_price'=>2500000,'image_url'=>'https://images.unsplash.com/photo-1555244162-803834f70033?w=400&h=300&fit=crop', 'rating'=>4.8, 'review_count'=>45,  'label'=>'best-seller', 'is_promo'=>true,  'is_new'=>false, 'description'=>'Paket 100 orang: buffet lengkap, minuman, snack, dan sound system'],
            ['name'=>'Paket Khitanan',           'category'=>'acara-khusus', 'price'=>800000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=400&h=300&fit=crop', 'rating'=>4.7, 'review_count'=>67,  'label'=>'popular',     'is_promo'=>false, 'is_new'=>false, 'description'=>'Paket untuk 40 orang: nasi kotak, lauk spesial, dessert, dan minuman'],

            // ── Iga ──
            ['name'=>'Iga Bakar Madu',             'category'=>'iga', 'price'=>75000, 'original_price'=>90000, 'image_url'=>'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>234, 'label'=>'best-seller', 'is_promo'=>true,  'is_new'=>false, 'description'=>'Iga sapi bakar dengan saus madu spesial, empuk dan juicy'],
            ['name'=>'Iga Penyet Sambal Bawang',   'category'=>'iga', 'price'=>65000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400&h=300&fit=crop', 'rating'=>4.8, 'review_count'=>189, 'label'=>'popular',     'is_promo'=>false, 'is_new'=>false, 'description'=>'Iga sapi goreng dipenyet dengan sambal bawang pedas dan lalapan'],
            ['name'=>'Iga Bakar Talam',            'category'=>'iga', 'price'=>85000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1558030006-450675393462?w=400&h=300&fit=crop', 'rating'=>4.9, 'review_count'=>156, 'label'=>'new',         'is_promo'=>false, 'is_new'=>true,  'description'=>'Iga sapi bakar disajikan di atas talenan dengan saus BBQ smoky'],
            ['name'=>'Sop Iga Sapi',               'category'=>'iga', 'price'=>55000, 'original_price'=>null,  'image_url'=>'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop', 'rating'=>4.7, 'review_count'=>267, 'label'=>'popular',     'is_promo'=>false, 'is_new'=>false, 'description'=>'Sop iga sapi kuah bening dengan wortel, kentang, dan buncis'],
            ['name'=>'Iga Bakar Rica',             'category'=>'iga', 'price'=>70000, 'original_price'=>80000, 'image_url'=>'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop', 'rating'=>4.8, 'review_count'=>198, 'label'=>'best-seller', 'is_promo'=>true,  'is_new'=>false, 'description'=>'Iga bakar dengan bumbu rica-rica pedas khas Manado'],
        ];

        foreach ($menus as $i => $menu) {
            Menu::create(array_merge($menu, [
                'is_stock'   => true,
                'is_active'  => true,
                'sold_count' => $menu['review_count'],
                'sort_order' => $i + 1,
            ]));
        }
    }
}
